### ISSUE TITLE
AmbiguousTimeError on crawl

### ISSUE THREAD

**Issue by sursh** [recursecenter/blaggregator#96]
A handful of blogs are throwing the following error when crawled in production. It was only three blogs on last crawl, so this is not super high priority. 

```
2014-11-02 01:00:00
Traceback (most recent call last):
  File "/app/home/management/commands/crawlposts.py", line 86, in handle_noargs
    self.crawlblog(blog)
  File "/app/home/management/commands/crawlposts.py", line 50, in crawlblog
    date = timezone.make_aware(date, timezone.get_default_timezone())
  File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/timezone.py", line 280, in make_aware
    return timezone.localize(value, is_dst=None)
  File "/app/.heroku/python/lib/python2.7/site-packages/pytz/tzinfo.py", line 349, in localize
    raise AmbiguousTimeError(dt)
AmbiguousTimeError: 2014-11-02 01:00:00
```

**Comment by punchagan** [comment]
This issue is no longer seen. Closing
